// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/Amorcito/Documents/NetBeansProjects/AnalizadorLexico/src/analizadorlexico/reglasLexicas.flex

package analizadorlexico;

import static analizadorlexico.Tokens.*;

@SuppressWarnings("fallthrough")
class ReglasLexicas {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\3\0\1\5\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\1\1\13\1\14\1\15\12\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\0\32\25\1\26\1\0\1\27"+
    "\1\30\1\25\1\0\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\25\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\25\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\20\24\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\0\1\37\1\40\1\41\1\42\1\43\1\2\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\12\24\1\52\7\24"+
    "\1\52\22\24\1\53\1\0\1\54\21\24\1\52\24\24"+
    "\1\15\33\24\1\52\40\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\65"+
    "\0\u0173\0\u01a8\0\u01dd\0\65\0\u0212\0\u0247\0\65\0\65"+
    "\0\u027c\0\u02b1\0\u02e6\0\65\0\u031b\0\65\0\65\0\65"+
    "\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3"+
    "\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b"+
    "\0\65\0\u06a0\0\65\0\65\0\65\0\65\0\65\0\u06d5"+
    "\0\65\0\65\0\65\0\65\0\65\0\u070a\0\65\0\65"+
    "\0\65\0\65\0\65\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813"+
    "\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb"+
    "\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u031b\0\u0b2e"+
    "\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6"+
    "\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e"+
    "\0\u0eb3\0\65\0\u0ee8\0\65\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc"+
    "\0\u0ff1\0\u1026\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164"+
    "\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c"+
    "\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u1691\0\u16c6\0\65\0\u16fb\0\u1730\0\u1765\0\u179a\0\u17cf"+
    "\0\u1804\0\u1839\0\u186e\0\u18a3\0\u18d8\0\u190d\0\u1942\0\u1977"+
    "\0\u19ac\0\u19e1\0\u1a16\0\u1a4b\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f"+
    "\0\u1b54\0\u1b89\0\u1bbe\0\u1bf3\0\u1c28\0\u1c5d\0\u1c92\0\u1cc7"+
    "\0\u1cfc\0\u1d31\0\u1d66\0\u1d9b\0\u1dd0\0\u1e05\0\u1e3a\0\u1e6f"+
    "\0\u1ea4\0\u1ed9\0\u1f0e\0\u1f43\0\u1f78\0\u1fad\0\u1fe2\0\u2017"+
    "\0\u204c\0\u2081\0\u20b6\0\u20eb\0\u2120\0\u2155\0\u218a\0\u21bf"+
    "\0\u21f4\0\u2229\0\u225e\0\u2293\0\u22c8\0\u22fd\0\u2332";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\25"+
    "\1\40\1\25\1\41\1\25\1\42\1\25\1\43\1\44"+
    "\1\45\1\46\1\25\1\47\1\50\3\25\1\51\1\52"+
    "\1\53\1\54\66\0\2\3\104\0\1\55\64\0\1\56"+
    "\50\0\1\57\71\0\1\60\73\0\1\61\54\0\1\62"+
    "\7\0\1\63\55\0\1\64\6\0\1\65\57\0\1\66"+
    "\4\0\1\67\60\0\1\16\67\0\1\70\1\71\64\0"+
    "\1\72\64\0\1\73\1\74\57\0\1\25\6\0\1\25"+
    "\3\0\30\25\22\0\1\25\6\0\1\25\3\0\1\25"+
    "\1\75\16\25\1\76\7\25\22\0\1\25\6\0\1\25"+
    "\3\0\15\25\1\77\1\25\1\100\6\25\1\101\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\1\102\6\25\1\103"+
    "\2\25\1\104\2\25\1\105\12\25\22\0\1\25\6\0"+
    "\1\25\3\0\4\25\1\106\10\25\1\107\12\25\22\0"+
    "\1\25\6\0\1\25\3\0\12\25\1\110\1\25\1\111"+
    "\10\25\1\112\2\25\22\0\1\25\6\0\1\25\3\0"+
    "\10\25\1\113\1\25\1\114\2\25\1\115\12\25\22\0"+
    "\1\25\6\0\1\25\3\0\15\25\1\116\12\25\22\0"+
    "\1\25\6\0\1\25\3\0\5\25\1\117\5\25\1\120"+
    "\1\121\13\25\22\0\1\25\6\0\1\25\3\0\15\25"+
    "\1\122\12\25\22\0\1\25\6\0\1\25\3\0\1\123"+
    "\3\25\1\124\23\25\22\0\1\25\6\0\1\25\3\0"+
    "\1\125\16\25\1\126\2\25\1\127\5\25\22\0\1\25"+
    "\6\0\1\25\3\0\4\25\1\130\23\25\22\0\1\25"+
    "\6\0\1\25\3\0\7\25\1\131\11\25\1\132\1\133"+
    "\1\25\1\134\1\25\1\135\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\7\25\1\136\7\25\1\137\10\25\22\0"+
    "\1\25\6\0\1\25\3\0\15\25\1\140\12\25\22\0"+
    "\1\25\6\0\1\25\3\0\7\25\1\141\20\25\66\0"+
    "\1\142\20\0\1\143\46\0\2\66\2\0\61\66\23\0"+
    "\1\144\57\0\1\25\6\0\1\25\3\0\20\25\1\145"+
    "\7\25\22\0\1\25\6\0\1\25\3\0\20\25\1\146"+
    "\7\25\22\0\1\25\6\0\1\25\3\0\15\25\1\147"+
    "\12\25\22\0\1\25\6\0\1\25\3\0\4\25\1\150"+
    "\23\25\22\0\1\25\6\0\1\25\3\0\21\25\1\151"+
    "\6\25\22\0\1\25\6\0\1\25\3\0\20\25\1\151"+
    "\1\152\6\25\22\0\1\25\6\0\1\25\3\0\1\115"+
    "\27\25\22\0\1\25\6\0\1\25\3\0\1\153\27\25"+
    "\22\0\1\25\6\0\1\25\3\0\14\25\1\154\13\25"+
    "\22\0\1\25\6\0\1\25\3\0\5\25\1\155\22\25"+
    "\22\0\1\25\6\0\1\25\3\0\22\25\1\156\5\25"+
    "\22\0\1\25\6\0\1\25\3\0\20\25\1\151\7\25"+
    "\22\0\1\25\6\0\1\25\3\0\22\25\1\157\5\25"+
    "\22\0\1\25\6\0\1\25\3\0\21\25\1\160\6\25"+
    "\22\0\1\25\6\0\1\25\3\0\14\25\1\161\13\25"+
    "\22\0\1\25\6\0\1\25\3\0\15\25\1\162\12\25"+
    "\22\0\1\25\6\0\1\25\3\0\17\25\1\117\10\25"+
    "\22\0\1\25\6\0\1\25\3\0\21\25\1\163\6\25"+
    "\22\0\1\25\6\0\1\25\3\0\16\25\1\164\11\25"+
    "\22\0\1\25\6\0\1\25\3\0\20\25\1\165\1\166"+
    "\6\25\22\0\1\25\6\0\1\25\3\0\14\25\1\167"+
    "\13\25\22\0\1\25\6\0\1\25\3\0\21\25\1\170"+
    "\6\25\22\0\1\25\6\0\1\25\3\0\24\25\1\117"+
    "\3\25\22\0\1\25\6\0\1\25\3\0\2\25\1\171"+
    "\25\25\22\0\1\25\6\0\1\25\3\0\10\25\1\172"+
    "\4\25\1\173\12\25\22\0\1\25\6\0\1\25\3\0"+
    "\1\25\1\174\26\25\22\0\1\25\6\0\1\25\3\0"+
    "\21\25\1\175\6\25\22\0\1\25\6\0\1\25\3\0"+
    "\15\25\1\176\12\25\22\0\1\25\6\0\1\25\3\0"+
    "\1\177\16\25\1\200\10\25\22\0\1\25\6\0\1\25"+
    "\3\0\16\25\1\201\11\25\22\0\1\25\6\0\1\25"+
    "\3\0\10\25\1\202\17\25\22\0\1\25\6\0\1\25"+
    "\3\0\14\25\1\203\13\25\22\0\1\25\6\0\1\25"+
    "\3\0\10\25\1\204\4\25\1\205\1\25\1\206\10\25"+
    "\22\0\1\25\6\0\1\25\3\0\1\207\25\25\1\117"+
    "\1\25\22\0\1\25\6\0\1\25\3\0\10\25\1\210"+
    "\1\25\1\211\15\25\22\0\1\25\6\0\1\25\3\0"+
    "\10\25\1\212\17\25\14\0\1\213\5\0\1\143\64\0"+
    "\1\25\6\0\1\25\3\0\21\25\1\214\6\25\22\0"+
    "\1\25\6\0\1\25\3\0\4\25\1\176\23\25\22\0"+
    "\1\25\6\0\1\25\3\0\12\25\1\215\15\25\22\0"+
    "\1\25\6\0\1\25\3\0\1\216\27\25\22\0\1\25"+
    "\6\0\1\25\3\0\4\25\1\117\23\25\22\0\1\25"+
    "\6\0\1\25\3\0\2\25\1\217\25\25\22\0\1\25"+
    "\6\0\1\25\3\0\20\25\1\204\7\25\22\0\1\25"+
    "\6\0\1\25\3\0\20\25\1\220\1\221\6\25\22\0"+
    "\1\25\6\0\1\25\3\0\1\222\27\25\22\0\1\25"+
    "\6\0\1\25\3\0\1\25\1\212\26\25\22\0\1\25"+
    "\6\0\1\25\3\0\13\25\1\117\14\25\22\0\1\25"+
    "\6\0\1\25\3\0\4\25\1\223\23\25\22\0\1\25"+
    "\6\0\1\25\3\0\1\224\27\25\22\0\1\25\6\0"+
    "\1\25\3\0\1\220\27\25\22\0\1\25\6\0\1\25"+
    "\3\0\15\25\1\117\12\25\22\0\1\25\6\0\1\25"+
    "\3\0\12\25\1\225\2\25\1\176\12\25\22\0\1\25"+
    "\6\0\1\25\3\0\21\25\1\226\6\25\22\0\1\25"+
    "\6\0\1\25\3\0\4\25\1\227\23\25\22\0\1\25"+
    "\6\0\1\25\3\0\6\25\1\117\21\25\22\0\1\25"+
    "\6\0\1\25\3\0\10\25\1\230\17\25\22\0\1\25"+
    "\6\0\1\25\3\0\11\25\1\231\16\25\22\0\1\25"+
    "\6\0\1\25\3\0\23\25\1\232\4\25\22\0\1\25"+
    "\6\0\1\25\3\0\21\25\1\233\6\25\22\0\1\25"+
    "\6\0\1\25\3\0\12\25\1\234\15\25\22\0\1\25"+
    "\6\0\1\25\3\0\22\25\1\235\5\25\22\0\1\25"+
    "\6\0\1\25\3\0\17\25\1\220\10\25\22\0\1\25"+
    "\6\0\1\25\3\0\21\25\1\234\6\25\22\0\1\25"+
    "\6\0\1\25\3\0\10\25\1\236\17\25\22\0\1\25"+
    "\6\0\1\25\3\0\4\25\1\115\23\25\22\0\1\25"+
    "\6\0\1\25\3\0\21\25\1\152\6\25\22\0\1\25"+
    "\6\0\1\25\3\0\2\25\1\237\25\25\22\0\1\25"+
    "\6\0\1\25\3\0\20\25\1\117\7\25\22\0\1\25"+
    "\6\0\1\25\3\0\24\25\1\204\3\25\22\0\1\25"+
    "\6\0\1\25\3\0\15\25\1\124\12\25\22\0\1\25"+
    "\6\0\1\25\3\0\14\25\1\240\13\25\22\0\1\25"+
    "\6\0\1\25\3\0\3\25\1\117\24\25\22\0\1\25"+
    "\6\0\1\25\3\0\1\241\27\25\22\0\1\25\6\0"+
    "\1\25\3\0\12\25\1\151\15\25\22\0\1\25\6\0"+
    "\1\25\3\0\17\25\1\242\10\25\22\0\1\25\6\0"+
    "\1\25\3\0\4\25\1\243\23\25\22\0\1\25\6\0"+
    "\1\25\3\0\11\25\1\117\16\25\22\0\1\25\6\0"+
    "\1\25\3\0\7\25\1\117\20\25\22\0\1\25\6\0"+
    "\1\25\3\0\21\25\1\117\6\25\22\0\1\25\6\0"+
    "\1\25\3\0\10\25\1\244\17\25\22\0\1\25\6\0"+
    "\1\25\3\0\22\25\1\245\5\25\22\0\1\25\6\0"+
    "\1\25\3\0\14\25\1\246\13\25\22\0\1\25\6\0"+
    "\1\25\3\0\12\25\1\247\15\25\22\0\1\25\6\0"+
    "\1\25\3\0\4\25\1\250\23\25\22\0\1\25\6\0"+
    "\1\25\3\0\1\251\27\25\22\0\1\25\6\0\1\25"+
    "\3\0\17\25\1\252\10\25\22\0\1\25\6\0\1\25"+
    "\3\0\23\25\1\151\4\25\22\0\1\25\6\0\1\25"+
    "\3\0\1\253\27\25\22\0\1\25\6\0\1\25\3\0"+
    "\1\101\27\25\22\0\1\25\6\0\1\25\3\0\4\25"+
    "\1\254\23\25\22\0\1\25\6\0\1\25\3\0\10\25"+
    "\1\255\17\25\22\0\1\25\6\0\1\25\3\0\17\25"+
    "\1\256\10\25\22\0\1\25\6\0\1\25\3\0\2\25"+
    "\1\257\25\25\22\0\1\25\6\0\1\25\3\0\7\25"+
    "\1\260\20\25\22\0\1\25\6\0\1\25\3\0\20\25"+
    "\1\261\7\25\22\0\1\25\6\0\1\25\3\0\21\25"+
    "\1\141\6\25\22\0\1\25\6\0\1\25\3\0\1\262"+
    "\27\25\22\0\1\25\6\0\1\25\3\0\1\256\27\25"+
    "\22\0\1\25\6\0\1\25\3\0\14\25\1\263\13\25"+
    "\22\0\1\25\6\0\1\25\3\0\12\25\1\220\15\25"+
    "\22\0\1\25\6\0\1\25\3\0\3\25\1\204\24\25"+
    "\22\0\1\25\6\0\1\25\3\0\12\25\1\264\15\25"+
    "\22\0\1\25\6\0\1\25\3\0\13\25\1\265\14\25"+
    "\22\0\1\25\6\0\1\25\3\0\14\25\1\266\13\25"+
    "\22\0\1\25\6\0\1\25\3\0\5\25\1\267\22\25"+
    "\22\0\1\25\6\0\1\25\3\0\6\25\1\151\21\25"+
    "\22\0\1\25\6\0\1\25\3\0\2\25\1\270\25\25"+
    "\22\0\1\25\6\0\1\25\3\0\2\25\1\117\25\25"+
    "\22\0\1\25\6\0\1\25\3\0\14\25\1\117\13\25"+
    "\22\0\1\25\6\0\1\25\3\0\21\25\1\271\6\25"+
    "\22\0\1\25\6\0\1\25\3\0\17\25\1\272\10\25"+
    "\22\0\1\25\6\0\1\25\3\0\10\25\1\273\17\25"+
    "\22\0\1\25\6\0\1\25\3\0\2\25\1\220\25\25"+
    "\22\0\1\25\6\0\1\25\3\0\22\25\1\151\5\25"+
    "\22\0\1\25\6\0\1\25\3\0\26\25\1\117\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\4\25\1\274\23\25"+
    "\22\0\1\25\6\0\1\25\3\0\2\25\1\275\25\25"+
    "\22\0\1\25\6\0\1\25\3\0\1\276\27\25\22\0"+
    "\1\25\6\0\1\25\3\0\21\25\1\277\6\25\22\0"+
    "\1\25\6\0\1\25\3\0\5\25\1\300\22\25\22\0"+
    "\1\25\6\0\1\25\3\0\15\25\1\301\12\25\22\0"+
    "\1\25\6\0\1\25\3\0\4\25\1\302\23\25\22\0"+
    "\1\25\6\0\1\25\3\0\14\25\1\303\13\25\22\0"+
    "\1\25\6\0\1\25\3\0\4\25\1\304\23\25\22\0"+
    "\1\25\6\0\1\25\3\0\2\25\1\151\25\25\22\0"+
    "\1\25\6\0\1\25\3\0\4\25\1\210\23\25\22\0"+
    "\1\25\6\0\1\25\3\0\16\25\1\117\11\25\22\0"+
    "\1\25\6\0\1\25\3\0\14\25\1\305\13\25\22\0"+
    "\1\25\6\0\1\25\3\0\14\25\1\220\13\25\22\0"+
    "\1\25\6\0\1\25\3\0\21\25\1\204\6\25\22\0"+
    "\1\25\6\0\1\25\3\0\15\25\1\306\12\25\22\0"+
    "\1\25\6\0\1\25\3\0\10\25\1\307\17\25\22\0"+
    "\1\25\6\0\1\25\3\0\5\25\1\117\22\25\22\0"+
    "\1\25\6\0\1\25\3\0\27\25\1\277\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9063];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\3\1\1\11\2\1\2\11"+
    "\3\1\1\11\1\1\3\11\20\1\1\11\1\1\5\11"+
    "\1\0\5\11\1\1\5\11\46\1\1\11\1\0\1\11"+
    "\46\1\1\11\74\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public String lexema;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ReglasLexicas(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Tokens yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { lexema=yytext(); return ERROR;
            }
          // fall through
          case 45: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 46: break;
          case 3:
            { lexema=yytext(); return NegacionLogica;
            }
          // fall through
          case 47: break;
          case 4:
            { lexema=yytext(); return Modulo;
            }
          // fall through
          case 48: break;
          case 5:
            { lexema=yytext(); return ANDBit;
            }
          // fall through
          case 49: break;
          case 6:
            { lexema=yytext(); return ParentesisAbierto;
            }
          // fall through
          case 50: break;
          case 7:
            { lexema=yytext(); return ParentesisCerrado;
            }
          // fall through
          case 51: break;
          case 8:
            { lexema=yytext(); return Multiplicacion;
            }
          // fall through
          case 52: break;
          case 9:
            { lexema=yytext(); return Suma;
            }
          // fall through
          case 53: break;
          case 10:
            { lexema=yytext(); return Resta;
            }
          // fall through
          case 54: break;
          case 11:
            { lexema=yytext(); return Punto;
            }
          // fall through
          case 55: break;
          case 12:
            { lexema=yytext(); return Division;
            }
          // fall through
          case 56: break;
          case 13:
            { lexema=yytext(); return Numero;
            }
          // fall through
          case 57: break;
          case 14:
            { lexema=yytext(); return DosPuntos;
            }
          // fall through
          case 58: break;
          case 15:
            { lexema=yytext(); return PuntoyComa;
            }
          // fall through
          case 59: break;
          case 16:
            { lexema=yytext(); return Menor;
            }
          // fall through
          case 60: break;
          case 17:
            { lexema=yytext(); return Asignacion;
            }
          // fall through
          case 61: break;
          case 18:
            { lexema=yytext(); return Mayor;
            }
          // fall through
          case 62: break;
          case 19:
            { lexema=yytext(); return OperadorTernario;
            }
          // fall through
          case 63: break;
          case 20:
            { lexema=yytext(); return Variable;
            }
          // fall through
          case 64: break;
          case 21:
            { lexema=yytext(); return CorcheteAbierto;
            }
          // fall through
          case 65: break;
          case 22:
            { lexema=yytext(); return CorcheteCerrado;
            }
          // fall through
          case 66: break;
          case 23:
            { lexema=yytext(); return XORBit;
            }
          // fall through
          case 67: break;
          case 24:
            { lexema=yytext(); return LlaveAbierta;
            }
          // fall through
          case 68: break;
          case 25:
            { lexema=yytext(); return ORBit;
            }
          // fall through
          case 69: break;
          case 26:
            { lexema=yytext(); return LlaveCerrada;
            }
          // fall through
          case 70: break;
          case 27:
            { lexema=yytext(); return NOTBit;
            }
          // fall through
          case 71: break;
          case 28:
            { lexema=yytext(); return Diferente;
            }
          // fall through
          case 72: break;
          case 29:
            { lexema=yytext(); return ModuloAsignacion;
            }
          // fall through
          case 73: break;
          case 30:
            { lexema=yytext(); return ANDLogico;
            }
          // fall through
          case 74: break;
          case 31:
            { lexema=yytext(); return MultiplicacionAsignacion;
            }
          // fall through
          case 75: break;
          case 32:
            { lexema=yytext(); return Incremento;
            }
          // fall through
          case 76: break;
          case 33:
            { lexema=yytext(); return SumaAsignacion;
            }
          // fall through
          case 77: break;
          case 34:
            { lexema=yytext(); return Decremento;
            }
          // fall through
          case 78: break;
          case 35:
            { lexema=yytext(); return RestaAsignacion;
            }
          // fall through
          case 79: break;
          case 36:
            { lexema=yytext(); return DivisionAsignacion;
            }
          // fall through
          case 80: break;
          case 37:
            { lexema=yytext(); return DesplazIzq;
            }
          // fall through
          case 81: break;
          case 38:
            { lexema=yytext(); return MenorIgual;
            }
          // fall through
          case 82: break;
          case 39:
            { lexema=yytext(); return Igual;
            }
          // fall through
          case 83: break;
          case 40:
            { lexema=yytext(); return MayorIgual;
            }
          // fall through
          case 84: break;
          case 41:
            { lexema=yytext(); return DesplazDer;
            }
          // fall through
          case 85: break;
          case 42:
            { lexema=yytext(); return PalabraReservada;
            }
          // fall through
          case 86: break;
          case 43:
            { lexema=yytext(); return ORLogico;
            }
          // fall through
          case 87: break;
          case 44:
            { lexema=yytext(); return DesplazDerSinSigno;
            }
          // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
